show_now:
  name: Show now
  fields:
    frame_id:
      required: true
      selector: {text: {}}
    asset_id:
      required: false
      selector: {text: {}}
next:
  name: Next image
  fields:
    frame_id:
      required: true
      selector: {text: {}}
previous:
  name: Previous image
  fields:
    frame_id:
      required: true
      selector: {text: {}}
refresh:
  name: Refresh
  fields:
    frame_id:
      required: true
      selector: {text: {}}
exclude_asset:
  name: Exclude asset from slideshow
  fields:
    frame_id:
      required: true
      selector: {text: {}}
    asset_id:
      required: true
      selector: {text: {}}
include_asset:
  name: Include asset in slideshow
  fields:
    frame_id:
      required: true
      selector: {text: {}}
    asset_id:
      required: true
      selector: {text: {}}
remove_asset:
  name: Remove asset from frame
  fields:
    frame_id:
      required: true
      selector: {text: {}}
    asset_id:
      required: true
      selector: {text: {}}
delete_asset:
  name: Delete asset permanently
  fields:
    asset_id:
      required: true
      selector: {text: {}}
